-- This SQL file for to create Streamlit app.
GRANT USAGE ON DATABASE CHATBOT_DB TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA CHATBOT_DB.CHATBOT_SCHEMA TO ROLE PUBLIC;
GRANT CREATE STREAMLIT ON SCHEMA CHATBOT_DB.CHATBOT_SCHEMA TO ROLE PUBLIC;
GRANT CREATE STAGE ON SCHEMA CHATBOT_DB.CHATBOT_SCHEMA TO ROLE PUBLIC;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PUBLIC;
GRANT USAGE ON WAREHOUSE cortex_search_wh TO ROLE PUBLIC;